// seeds/02-fields.js
export async function seed(knex) {
  // await knex("module_fields").truncate();
  await knex("module_fields").insert([
    {
      name: "componentName",
      label: "Component Name",
      hint: "Used as an index in the application, must be unique",
      moduleId: 1,
      componentId: 10,
      isDefault: 1,
    },
    {
      name: "label",
      label: "Component Label",
      hint: "The Component label which is displayed for the user",
      moduleId: 1,
      componentId: 10,
    },
    {
      name: "name",
      label: "Module Name",
      hint: "Used as an index in the application, must be unique",
      moduleId: 2,
      componentId: 10,
      isDefault: 1,
    },
    {
      name: "label",
      label: "Module Label",
      hint: "The module label which is displayed for the user",
      moduleId: 2,
      componentId: 10,
    },
    { name: "url", label: "Field Label", moduleId: 2, componentId: 10 },
    {
      name: "name",
      label: "Field Name",
      hint: "Used as an index in the application, must be unique",
      moduleId: 3,
      componentId: 10,
      isDefault: 1,
    },
    {
      name: "label",
      label: "Field Label",
      hint: "The field label which is displayed for the user",
      moduleId: 3,
      componentId: 10,
    },
    { name: "hint", label: "Field Hint", moduleId: 3, componentId: 10 },
    {
      name: "moduleId",
      label: "Related Module",
      moduleId: 3,
      referenceModuleId: 2,
      componentId: 1,
    },
    {
      name: "componentId",
      label: "Component",
      moduleId: 3,
      referenceModuleId: 1,
      componentId: 1,
    },
    {
      name: "referenceModuleId",
      label: "Foreign Module",
      moduleId: 3,
      referenceModuleId: 2,
      componentId: 1,
    },
    {
      name: "configuration",
      label: "Field Configuration",
      moduleId: 3,
      componentId: 37,
    },
    {
      name: "isDefault",
      label: "Is Default",
      moduleId: 3,
      componentId: 21,
    },
    {
      name: "isFormField",
      label: "Is Form Field",
      moduleId: 3,
      componentId: 21,
    },
    {
      name: "isDeleted",
      label: "Is Deleted Field",
      moduleId: 3,
      componentId: 21,
    },
    {
      name: "parentFieldId",
      label: "Parent Row",
      moduleId: 3,
      referenceModuleId: 3,
      componentId: 1,
    },
    {
      name: "label",
      label: "Label",
      hint: "",
      moduleId: 5,
      componentId: 10,
    },
    {
      name: "menuGroupId",
      label: "Menu Group",
      hint: "",
      moduleId: 2,
      componentId: 1,
    },
  ]);
}
